fix updating items in the quick-pick menu
eclipse-theia/theia pull request #10055
Opened 2021-09-06 12:24 UTC by vinokurig

Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

#### What it does

Fixes a bug when quick pick items are not updated on the fly.

#### How to test

1. Clone and compile the test plugin: https://github.com/microsoft/vscode-extension-samples/tree/main/quickinput-sample
2. Start hosted plugin
3. Execute the `Quick Input Samples` from the command palette.
4. Choose `quickOpen` and type something to the input box.

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2021-09-06 12:28 UTC, tsmaeder commented
@vinokurig can you describe what the fix does in the code? I.e. what is that basic idea of the code changes in the fix?

2021-09-06 13:01 UTC, vinokurig commented
@tsmaeder 
> @vinokurig can you describe what the fix does in the code? I.e. what is that basic idea of the code changes in the fix? Also, what was the cause of the bug? Remember to "write shit down" (TM)

Updated the description

2021-09-07 07:41 UTC, tsmaeder commented
@vinokurig I think your change takes the code in the wrong direction: instead of adding "currentInput" state into the `QuickInputService`, we should add a "createQuickPick" method to the interface and use that in the `quick-open-main.ts#$showCustomQuickPick`.  The current change fails when someone calls `QuickInputService#showQuickPick` twice in a row. There have been a number of things wrong with this area of the code for a long time which are not your fault, but we should refrain from making the situation worse.

2021-09-07 07:42 UTC, tsmaeder requested changes
See comment on the main page for the reasons.

2021-09-08 13:54 UTC, vinokurig commented
Opened a PR with different approach https://github.com/eclipse-theia/theia/pull/10065

2021-09-08 13:54 UTC, closed without merging