fix(application-package): Fix the return value error of electron.isDevMode API in Windows system in development mode.
eclipse-theia/theia pull request #10359
Opened 2021-11-01 09:12 UTC by zhaomenghuan

#### What it does

Fix the return value error of electron.isDevMode API in Windows system in development mode.

#### How to test

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: zhaomenghuan <zhaomenghuan02@meituan.com>

2021-11-01 10:38 UTC, msujew reviewed
Hi @zhaomenghuan, thank you for your contribution, do you mind adding testing steps to your PR?

2021-11-01 11:55 UTC, zhaomenghuan commented
> Hi @zhaomenghuan, thank you for your contribution, do you mind adding testing steps to your PR?

Ok, I added a test description

2021-11-01 12:24 UTC, msujew approved these changes
I can confirm that the issue exists on `master` and is addressed by this change 👍 

As I can't imagine it leading to regressions on other OS, I'll approve this.

2021-11-09 19:05 UTC, paul-marechal requested changes

2021-11-09 19:05 UTC, paul-marechal commented on dev-packages/application-package/src/environment.ts
> +            && ((process as any).defaultApp || /node_modules[/|\\]electron[/|\\]/.test(process.execPath)); // eslint-disable-line @typescript-eslint/no-explicit-any
We don't need the `|` symbol here.

2021-11-13 15:28 UTC, zhaomenghuan commented on dev-packages/application-package/src/environment.ts
> +            && ((process as any).defaultApp || /node_modules[/|\\]electron[/|\\]/.test(process.execPath)); // eslint-disable-line @typescript-eslint/no-explicit-any
Thank you，I modified the code.

2021-11-22 17:23 UTC, merged