Add support for `PluginContext.logUri` and PluginContext.extension`
eclipse-theia/theia pull request #10458
Opened 2021-11-24 17:54 UTC by Archie27376

#### What it does
Fixes #10033
The commit adds the properties `logUri` and `extension` to the `PluginContext` interface and enables their support.

#### How to test

#### Review checklist

- [X] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2021-12-06 09:08 UTC, tsmaeder commented
> @tsmaeder would you happen to know how to get a plugin instance when we set the extension's context, else we would need to try and re-construct the fields. 

Sorry, not quite sure what you refer to, here. Can you point to some code?

> Also, do you know why the interface `Plugin` refers to "plugin" while in vscode it is referenced as "Extension"?

To confuse unwary programmers ;-). No, since there were already "extensions" in the Theia programming model, the runtime extension modules (called "extensions" in VS Code) were named"plugins". The choice to reflect that in the Theia plugin API namespace was unfortunate, IMO, but it's easy to complain after the fact. 🤷 

Personally, my evil plan is to deprecate most of the "theia" API namespace and to only have stuff in there that is not available in the "vscode" namespace. The duplication does not make much sense, IMO. But that won't happen today or tomorrow.

2021-12-06 09:23 UTC, tsmaeder requested changes

2021-12-06 09:23 UTC, tsmaeder commented on packages/plugin-ext/src/plugin/plugin-manager.ts
> +            extension: plugin,
The `plugin` variable here is an instance of `plugin-apr-rpc.ts/Plugin`, but we need an instance of `theia.Plugin` here. `plugin-context.ts#723`, etc. shows how to convert between them.

2022-01-17 13:00 UTC, vince-fugnitto commented
@martin-fleck-at thank you for your interest, @Archie27376 is no longer an intern on the project so I'm not sure if he is currently available or interested in finishing the pull-request, if you'd like to pick up the pull-request please go ahead!

2022-01-18 08:45 UTC, martin-fleck-at commented
@vince-fugnitto Thank you for letting me know! I'll try to have a look at this as soon as possible but definitely some time this week.

2022-01-19 14:08 UTC, martin-fleck-at commented
Since I cannot push to the private branch, I created a new PR in https://github.com/eclipse-theia/theia/pull/10650

2022-01-26 15:55 UTC, JonasHelming commented
I am clsoing this PR as it has been contributed in #10650

2022-01-26 15:55 UTC, closed without merging