Move Theme Loading into Inversify Lifecycle
eclipse-theia/theia pull request #11213
Opened 2022-05-27 18:26 UTC by colin-grant-work

#### What it does

At the moment, the initialization of the theming happens outside of the application's `inversify` lifecycle. That makes it difficult to override and difficult to integrate into the management of `monaco`'s initialization lifecycle. Part of the reason for attempting to complete theme initialization outside of the `inversify` lifecycle is to ensure that themes applied accurately even to the loading screen. That seems unnecessary to me: the point of a loading screen is to give the application time to do its work. This PR sets the background of the loading screen to a constant.

#### How to test

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2022-06-02 14:18 UTC, msujew approved these changes
@colin-grant-work I'm wondering whether we can reintroduce storing the theme color for the loading screen later. I guess it is out of scope for this PR. As far I can tell you also are interested in it for https://github.com/eclipse-theia/theia/issues/10345, right?

Anyway, regarding the changes: I'm quite happy with them. Simplify my current work on https://github.com/eclipse-theia/theia/issues/11063 a bit 👍 As there's no noticeable regression, I'll approve this.

2022-06-02 14:46 UTC, colin-grant-work commented on packages/core/src/browser/shell/shell-layout-restorer.ts
> +            this.themeService.reset(); // Theme service cannot use DI, so the current theme ID is stored elsewhere. Hence the explicit reset.
Good point. It is not. I'll remove it. 👍

2022-06-02 16:06 UTC, msujew commented
> Would you rather keep the dynamic background, then?

Yeah, I think that would be preferable, if it's not too much work. Maybe something that could be solved with the `preloader.ts`? ;)

2022-06-09 18:30 UTC, colin-grant-work commented
@msujew, I have brought back the code to save and load the theme color between sessions, and modified some of the startup code surrounding it to try to avoid theme flashes.

2022-06-10 16:18 UTC, msujew requested changes
When loading Theia for the first time with the newest changes (can be triggered manually by removing all `idb` and `localStorage` data), theme data isn't applied for some reason:

![image](https://user-images.githubusercontent.com/4377073/173088013-651efc95-e1c3-4f9b-b752-dfa8cf7191c4.png)

With the previous commit everything works correctly

2022-06-14 16:10 UTC, colin-grant-work commented
> When loading Theia for the first time with the newest changes (can be triggered manually by removing all `idb` and `localStorage` data), theme data isn't applied for some reason:

Thanks for catching this. I have tried to fix the startup routine here for the different cases.
1. If the `ThemeServiceWithDB` loads the theme from its database rather than its `theme` object, `setCurrentTheme` was previously failing, because it expected the theme to be in the `theme` object unconditionally. I have added code to add the theme from the database to the `theme` object.
2. If no theme was set in local storage, then the entire `loadUserTheme` routine ran before the `ColorApplicationContribution` attached its listener for theme changes, so its `update` method was never called. I have added code that calls `update` when the `ThemeService` declares that it has completed the `loadUserTheme` routine.

2022-06-15 13:54 UTC, colin-grant-work commented
@msujew, sounds good. I'll do it now.

2022-06-15 13:55 UTC, merged