Dispatch the IDE's theme based on the OS' theme.
eclipse-theia/theia pull request #11570
Opened 2022-08-15 09:37 UTC by kittaakos

#### What it does

From now on, the default IDE theme may dispatch on the OS theme.

In action:

https://user-images.githubusercontent.com/1405703/184612250-c4aebb72-5d64-4b65-b47c-79b8960d1cc1.mp4

Changed the `defaultTheme` type from `string` to `string | { light: string, dark: string }`.

#### How to test

 - `workbench.colorTheme` is not present in workspace/user `settings.json`,
 - set the OS theme light, load the IDE, the `light` theme will be active,
 - set the OS theme dark, load the IDE, the `dark` theme is active. 

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2022-08-15 13:22 UTC, kittaakos commented
// CC @francescospissu

2022-09-01 14:10 UTC, kittaakos commented
I appreciate your time reviewing the PR.

> Do you mind adding a breaking change entry for 1.30? As the `defaultTheme` property is no longer just `string`, it might be breaking for people that consume the value in some way.

Thanks for the heads-up. Let me know if you're OK with the updates in the breaking changes.


----

I have noticed this:

https://github.com/eclipse-theia/theia/blob/af83aaa66b51e9da92f43d828837e020216bf085/packages/core/src/browser/preloader.ts#L61

Would it make sense to dispatch the default background color based on the OS theme? So when the OS theme is not-dark, maybe Theia could fall back to the light [`editor.background`](https://github.com/eclipse-theia/theia/blob/af83aaa66b51e9da92f43d828837e020216bf085/packages/monaco/data/monaco-themes/vscode/light_vs.json#L5) instead of [`#1E1E1E`](https://github.com/eclipse-theia/theia/blob/af83aaa66b51e9da92f43d828837e020216bf085/packages/monaco/data/monaco-themes/vscode/dark_vs.json#L5). What do you think?

2022-09-01 14:15 UTC, msujew commented
> Would it make sense to dispatch the default background color based on the OS theme? So when the OS theme is not-dark, maybe Theia could fall back to the light [editor.background](https://github.com/eclipse-theia/theia/blob/af83aaa66b51e9da92f43d828837e020216bf085/packages/monaco/data/monaco-themes/vscode/light_vs.json#L5) instead of [#1E1E1E](https://github.com/eclipse-theia/theia/blob/af83aaa66b51e9da92f43d828837e020216bf085/packages/monaco/data/monaco-themes/vscode/dark_vs.json#L5). What do you think?

@kittaakos Yeah, dispatching based on the OS theme while loading also seems pretty reasonable to me 👍

2022-09-01 14:17 UTC, msujew commented on CHANGELOG.md
> +- [core] Changed type of `FrontendApplicationConfig#defaultTheme` from `string` to `DefaultTheme`. From now on, the default theme can dispatched based on the OS theme. Use `DefaultTheme#defaultForOST
Minor: typo 
```suggestion
- [core] Changed type of `FrontendApplicationConfig#defaultTheme` from `string` to `DefaultTheme`. From now on, the default theme can be dispatched based on the OS theme. Use `DefaultTheme#defaultForOSTheme` to derive the `string` theme ID.
```

2022-09-02 08:42 UTC, kittaakos commented
I have updated the PR. Please let me know if anything else needs to be adjusted. Thank you!

2022-09-07 17:49 UTC, msujew requested changes
With the proposed changes below everything looks good. I'll approve after my comments are addressed.

2022-09-07 17:49 UTC, msujew commented on packages/core/src/browser/preloader.ts
> +    const value = window.localStorage.getItem(DEFAULT_BACKGROUND_COLOR_STORAGE_KEY) || dark ? '#1E1E1E' : '#FFFFFF';
This expression doesn't work as expected, as `||` takes higher precedence than the ternary operator here. So `window.localStorage.getItem(DEFAULT_BACKGROUND_COLOR_STORAGE_KEY) || dark` is evaluated first, leading to the `value` being always `#1E1E1E` if the localstorage value is set.
```suggestion
    const value = window.localStorage.getItem(DEFAULT_BACKGROUND_COLOR_STORAGE_KEY) || (dark ? '#1E1E1E' : '#FFFFFF');
```

2022-09-07 17:49 UTC, msujew commented on CHANGELOG.md
> +- [core] Changed type of `FrontendApplicationConfig#defaultTheme` from `string` to `DefaultTheme`. From now on, the default theme can be dispatched based on the OS theme. Use `DefaultTheme#defaultFor
Suggestion: Please move this to the breaking changes for `1.30.0`.

2022-09-08 09:45 UTC, msujew approved these changes
Alright, looks good to me 👍

2022-09-08 09:53 UTC, merged