Submenu contribution to editor/title and view/title not working #12706
eclipse-theia/theia pull request #12814
Opened 2023-08-08 13:34 UTC by jfaltermeier

#### What it does

The menu registered at the registry is correctly registered (Context menu > Sub Menu > Child Entries). 

In this case the renderer should skip rendering the sub menu however. 
The sub menu is represented by the toolbar button and its tooltip already. 
So we just want to see the child entries in the context menu. 

This PR introduces a helper method to adjust an existing menu-model to be rendered without a single root-submenu. Renderers may use this helper as required.  

* introduce option in RenderContextMenuOptions to ask renderer to not render a menu with single submenu. Instead render only the children
* add helper method to menu-model-registry to remove the parent nodes from a menu node as described above
* adjust renderers and callers accordingly
* fix icons in toolbar

fixes #12706

![Peek 2023-08-08 15-31](https://github.com/eclipse-theia/theia/assets/5889696/4218bdf1-e894-4740-a176-67e4f7468f54)

#### How to test
See the reproducer on #12706

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2023-08-09 06:27 UTC, JonasHelming commented
@jonah-iden You mentioned yesterday that you miss some menus, is this maybe related?

2023-08-09 06:41 UTC, jonah-iden commented
@JonasHelming thanks for the info, but the not notebook specific menus im missing are:
`file/newFile` from btoh the python and ipynb extension and `editor/content` which only the python extension is missing.
All other missing menus are notebook specific, so i have to add them myself

2023-08-09 06:43 UTC, JonasHelming commented
https://github.com/eclipse-theia/theia/issues/12755

2023-08-17 07:36 UTC, martin-fleck-at requested changes
Code looks good to me in general and as far as I can see, all the menus are showing their content as they do in VS Code, even if the location within the context menu sometimes varies a bit. So great work, Johannes!

The only issue I could detect was with the icon. For some reason, it does not show up for me. I looked a bit into this and the image resource is properly hosted and loaded so it seems more of a CSS thing. The CSS is applied in `plugin-shared-style.ts` and I noticed that if I change the `display` property from the default `inline` to something else, the icon shows up. However, I'm not sure if this might have some side effects on other icons. Could you please have another look?

2023-08-17 12:16 UTC, jfaltermeier commented
> Code looks good to me in general and as far as I can see, all the menus are showing their content as they do in VS Code, even if the location within the context menu sometimes varies a bit. So great work, Johannes!
> 
> The only issue I could detect was with the icon. For some reason, it does not show up for me. I looked a bit into this and the image resource is properly hosted and loaded so it seems more of a CSS thing. The CSS is applied in `plugin-shared-style.ts` and I noticed that if I change the `display` property from the default `inline` to something else, the icon shows up. However, I'm not sure if this might have some side effects on other icons. Could you please have another look?

Thanks, I can reproduce it when I merge the current master into my branch. I think you mentioned that you've rebased before testing. Looks like https://github.com/eclipse-theia/theia/pull/12827 causes the issue for my previous fix. I'll have a look.

2023-08-17 14:27 UTC, jfaltermeier commented
I've added a dedicated css entry that sets `display` to `flex`. With this it seems to work. 

I also noticed an issue with the `removeSingleRootNode` method while retesting. It did not detect submenus that are not rendered (because they have no children) as something that can be skipped as well. This was reproducible immediately after installing the test vsix. 
Please have a look at the implementation again.

2023-08-17 15:03 UTC, martin-fleck-at commented on packages/core/src/common/menu/menu-model-registry.ts
> +    private allChildrenCompound(children: ReadonlyArray<MenuNode>): boolean {
I'd prefer this method to be protected.

2023-08-17 15:03 UTC, martin-fleck-at commented on packages/core/src/common/menu/menu-model-registry.ts
> +    private isEmpty(children: ReadonlyArray<MenuNode>): boolean {
I'd prefer this method to be protected.

2023-08-18 11:17 UTC, jfaltermeier commented on packages/core/src/common/menu/menu-model-registry.ts
> +            if (!this.isEmpty(child.children!)) {
We did a check that all children are CompoundMenuNodes before, but I can add it

2023-08-18 11:33 UTC, jfaltermeier commented
> Hello Johannes, thank you for the quick update! Everything looks good to me now, I just have a minor nitpick regarding private methods in classes that may be re-used by adopters. Please let me know what you think.

Thanks for the review. I've made the methods protected, although I would prefer them to be private. I understand why you prefer it the other way, but those methods are only existing, because we use them as helper methods from one the the actual API methods to make the code nicer. If this implementation has to change at some point, we still have the burden of having those additional API methods that can't be removed/adapted without a major API break. So I'm not a fan.

2023-08-21 13:24 UTC, martin-fleck-at approved these changes
Thank you Johannes, everything looks good to me now!

2023-08-21 13:25 UTC, merged