bugfix/12892 Localizes plugin rintime error notification
eclipse-theia/theia pull request #12893
Opened 2023-09-04 11:09 UTC by Zebsterpasha

#### What it does
Fixes #12892 

#### How to test
Just check the localization keys

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2023-09-05 11:55 UTC, vince-fugnitto commented on packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts
> +            hintMessage = nls.localize('theia/plugin-ext/runtimeErrorAddHingMessage', 'Probably there is not enough memory for the plugins. ') + hintMessage;
minor - typo:

```suggestion
            hintMessage = nls.localize('theia/plugin-ext/runtimeErrorAddingMessage', 'Probably there is not enough memory for the plugins. ') + hintMessage;
```

---

I believe we can simplify to `runtimeMemoryError`,

2023-09-11 08:52 UTC, msujew commented on packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts
> +            hintMessage = nls.localize('theia/plugin-ext/runtimeMemoryError', 'Probably there is not enough memory for the plugins. ') + hintMessage;
Minor: Whitespace can sometimes get lost in automatic translation.
```suggestion
            hintMessage = `${nls.localize('theia/plugin-ext/runtimeMemoryError', 'Probably there is not enough memory for the plugins.')} {hintMessage}`;
```

2023-09-12 09:37 UTC, msujew requested changes
Looking over this, I've noticed that this code actually resides in the backend part of the application. While `nls.localize` is callable from backend code, it will always return the english default value. This approach to fixing this issue isn't working.

In theory, you will need a dedicated frontend service that performs the `MessageService#error` call with a localized value.

2023-10-11 11:38 UTC, Zebsterpasha commented
@msujew This problem is not critical for me, I will not be able to fix it in the near future.

2023-10-11 11:41 UTC, closed without merging

2023-10-11 11:41 UTC, msujew commented
Alright, let's close it for now. Maybe someone else will take inspiration from this to fix the issue.