Ensure we do not spam the log in the RpcProxyFactory
eclipse-theia/theia pull request #13191
Opened 2023-12-19 11:56 UTC by martin-fleck-at

#### What it does

Fixes https://github.com/eclipse-theia/theia/issues/13189

#### How to test

- Produce an error in any Rpc-based communication, e.g., Theia frontend-backend
- Watch the error being logged in the console even if you catch it

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2024-01-16 10:17 UTC, tortmayr requested changes

2024-01-16 17:14 UTC, martin-fleck-at commented on packages/core/src/common/messaging/proxy-factory.ts
> +            this.logger?.error(`Request ${method} failed with error: ${reason}`, stack);
That is also a good option and fine with me! I pushed another commit to simply remove all the logging.

2024-01-17 12:47 UTC, tortmayr approved these changes
LGTM!

2024-01-17 12:48 UTC, merged

2024-01-20 19:38 UTC, persuasive-pipe-402217 reviewed
@tonoese1994