Improved vsocde tabApi
eclipse-theia/theia pull request #13730
Opened 2024-05-24 12:04 UTC by jonah-iden

#### What it does

This improves and fixes some things for the vscode tab api.
- Now there should always be a default tabGroup open, even when no tabs are open
- implements the viewCollumn property
- smaller fix for to many tab events being fired

#### How to test

Here is a small test extension.
This shows message and logs into the console the different tabApi events.

#### Follow-ups

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2024-05-24 13:11 UTC, tsmaeder commented
@jonah-iden do we have a list of issues this PR fixes?

2024-05-24 13:24 UTC, jonah-iden commented
It can easily be that i overlooked problems. Its sadly super hard to align this perfectly to vscode because phosphor is just doing things differently to vscodes layouting. Like events just happening in different order

2024-05-24 13:34 UTC, tsmaeder commented
https://github.com/eclipse-theia/theia/issues/12702
https://github.com/eclipse-theia/theia/issues/13674

Also, we should try to remove the workaround in the tests I introduced for the 1.88.1 built-ins. https://github.com/eclipse-theia/theia/issues/13679#issuecomment-2094653160

2024-05-24 13:42 UTC, tsmaeder commented
Removing the workaround for https://github.com/eclipse-theia/theia/issues/13679 makes the tests fail again. Seems that one at least is still there.

2024-05-27 06:40 UTC, jonah-iden commented on packages/plugin-ext/src/main/browser/tabs/tabs-main.ts
> +            .concat(newTabbar ? [newTabbar] : [])
yeah thats an event ordering issue. There is sadly no way we can hook in to an event after the toolbar is added but before the widget is, so we need to add this here

2024-05-27 14:22 UTC, tsmaeder requested changes
Otherwise, looks good to me.

2024-05-27 14:22 UTC, tsmaeder commented on examples/api-tests/src/typescript.spec.js
> -        await timeout(1000); // workaround for https://github.com/eclipse-theia/theia/issues/13679
Also, I need the 1 second timeout for the tests to run reliably, locally.

2024-05-29 16:06 UTC, msujew commented on examples/api-tests/src/typescript.spec.js
> -        await timeout(1000); // workaround for https://github.com/eclipse-theia/theia/issues/13679
The `typescript.isManagedFile` context key is working unreliably. When opening a TypeScript file in the editor and querying the context key value, I always get `false`, even though a TypeScript editor is open (and focused).

I've reinstated the 1 second timeout, as the issue seems to be unrelated to the tab API.

2024-05-29 16:10 UTC, msujew commented
@tsmaeder FYI the latest commit fixes an error in the plugin host that appeared due to an off-by-one error. Note that the `typescript.isManagedFile` context key seems to work unreliably and cannot be used to check whether the TypeScript language services are available (or not). See also https://github.com/eclipse-theia/theia/pull/13730#discussion_r1619148021. This could be potentially fixed in a separate PR. However it fixes the initial issue that causes https://github.com/eclipse-theia/theia/issues/13674, to this PR should be good to go.

2024-05-30 07:24 UTC, tsmaeder commented on examples/api-tests/src/typescript.spec.js
> +        await timeout(1000);
```suggestion
        await timeout(1000);// workaround for https://github.com/eclipse-theia/theia/issues/13679
```

2024-05-30 07:25 UTC, tsmaeder commented on examples/api-tests/src/typescript.spec.js
> +        await timeout(1000);
We should keep the reference in order to mark the workaround

2024-05-30 11:14 UTC, msujew commented
FYI I believe I've mostly fixed https://github.com/eclipse-theia/theia/issues/13679, it's just a minor issue left: The `onDidChangeActiveTextEditor` event is fired on the plugin host before the tab API has been updated on the plugin host (due to the order of events in the frontend). However, I couldn't find a quick way to fix this without breaking a bunch of other stuff, so I'm putting this off for a separate PR.

The original off-by-one issue mentioned in the issue is fixed, it's just a matter of correctly ordering the events.

2024-05-30 12:16 UTC, tsmaeder approved these changes

2024-05-30 12:19 UTC, merged