Support for "--headless-hosted-plugin-inspect" cmd argument
eclipse-theia/theia pull request #13918
Opened 2024-07-12 08:12 UTC by jfaltermeier

#### What it does

* add names for plugin servers that will be used on the command line like `--server-name-inspect`
* enable `--headless-hosted-plugin-inspect`
* add plugin-dev preferences for specifying ports per plugin-server via the new server-name

closes #13462 

#### How to test

See instructions on the ticket https://github.com/eclipse-theia/theia/issues/13462

#### Follow-ups

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2024-07-21 12:31 UTC, martin-fleck-at requested changes
Change looks good to me and works very well, thank you Johannes! I do have a few questions and some small nitpicks but nothing major.

2024-08-05 13:53 UTC, jfaltermeier commented on packages/plugin-ext/src/hosted/node/plugin-service.ts
> +        this.serverName = this.getServerName();
I'll remove the property

2024-08-05 13:56 UTC, jfaltermeier commented on packages/plugin-dev/src/browser/hosted-plugin-manager-client.ts
> +                            debugPort: [... this.hostedPluginPreferences['hosted-plugin.debugPorts']]
It should be the "Hosted Plugin: Restart Instance" command, but I think this does not corretely identify whether there is a running hosted plugin. It always says "Hosted Plugin: Starting" for me (also before my changes) .

2024-08-05 14:02 UTC, martin-fleck-at commented on packages/plugin-dev/src/browser/hosted-plugin-manager-client.ts
> +                            debugPort: [... this.hostedPluginPreferences['hosted-plugin.debugPorts']]
Right, if that is the case I think we can ignore it for this PR. Could you please log an issue for that?

2024-08-05 14:03 UTC, martin-fleck-at approved these changes
Thank you for the quick update! Change looks good to me.

2024-08-05 14:08 UTC, merged