feat: show variables and function on ai agent configuration
eclipse-theia/theia pull request #14177
Opened 2024-09-16 15:30 UTC by eneufeld

#### What it does

The agent configuration now shows also the variables (global and agent specific) as well as the functions that the agents uses. If a variable or function is used in the prompt but is not declared by the agent then this is also marked in the view.

All agents are updated to declare the variables and functions they use.

fixes #14133

#### How to test

Open the AI Configuration View and see that variables and functions are shown.
If you modify the prompt the list is dynamically updated.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2024-09-18 14:10 UTC, sdirix requested changes
The "Ai Terminal Agent" uses the `cwd` variable, however in its list it shows up as "not used". I guess that's because it's also a global variable? Is it one?

![image](https://github.com/user-attachments/assets/75dade4a-45d1-48fb-889a-33dcbb0134d7)

---

Variables which couldn't be mapped are shown as agent-specific: 
![image](https://github.com/user-attachments/assets/db0276e4-a39f-4722-853a-7623e696a8f1)

Does this make sense or should we rather show them in an own optional section which only exists if there is at least one? e.g. "Unmapped variables used in prompt(s)"

---

I think we should render a replacement text like "None" into empty sections:

![image](https://github.com/user-attachments/assets/5e2022ee-9ebc-44f9-9571-1488ed0c8669)

---

Agent specific variables should not be clickable / show a different pointer as nothing happens when you click them

![image](https://github.com/user-attachments/assets/337a60ef-ce7e-4b1b-b4a3-ec49bb477d64)

2024-09-18 20:38 UTC, JonasHelming commented
"Does this make sense or should we rather show them in an own optional section which only exists if there is at least one? e.g. "Unmapped variables used in prompt(s)"

I think it does. The most likely case for this is that an agent is using an agent-specific variable and has not declared its usage. All other cases (not mapped to a global) are error cases.

2024-09-18 21:42 UTC, eneufeld commented on packages/ai-code-completion/src/common/code-completion-agent.ts
> +        { name: 'MARKER', usedInPrompt: true, description: 'The position where the completion should be inserted.' }
Currently it has the same identifier as a variable thus it is discovered by our parser and needs to be added here.
With your PR this is not an issue anymore and can be removed from the list.

2024-09-18 21:52 UTC, eneufeld commented
For the cwd case the current logic checks that if a prompt variable is part of the global variables list => then it goes to the global section
So we assume that the agent implementer is not right.
We could modify this and assume the implementer is correct so if a variable is defined in the list of agent specific variables then it wins over it being in the global variables list.

@JonasHelming what is your take?

2024-09-19 00:07 UTC, eneufeld commented on packages/ai-core/src/browser/ai-configuration/agent-configuration-widget.tsx
> +            const prompt = storedPrompt?.template ?? template.template;
this probably never happens, but the storedPrompt can be undefined so I wanted to have a fallback in place.

2024-09-19 07:16 UTC, sdirix commented
> For the cwd case the current logic checks that if a prompt variable is part of the global variables list => then it goes to the global section So we assume that the agent implementer is not right. We could modify this and assume the implementer is correct so if a variable is defined in the list of agent specific variables then it wins over it being in the global variables list.
> 
> @JonasHelming what is your take?

In the case of `cwd`, the terminal agent specifically hands in the variable. The global one is not used.

2024-09-19 07:18 UTC, eneufeld commented
> > For the cwd case the current logic checks that if a prompt variable is part of the global variables list => then it goes to the global section So we assume that the agent implementer is not right. We could modify this and assume the implementer is correct so if a variable is defined in the list of agent specific variables then it wins over it being in the global variables list.
> > @JonasHelming what is your take?
> 
> In the case of `cwd`, the terminal agent specifically hands in the variable. The global one is not used.

Yes, there is also a second case of the same behavior somewhere.
We just don't know what the agent implementation does. We need to decide who we believe.

2024-09-19 12:16 UTC, sdirix commented on packages/ai-code-completion/src/common/code-completion-agent.ts
> +        { name: 'MARKER', usedInPrompt: true, description: 'The position where the completion should be inserted.' }
The other PR was merged, so we need to adjust this PR for the new prompt variables. Otherwise the prompt and variables will not align on `master`

2024-09-19 13:52 UTC, sdirix approved these changes
Works for me! Thanks!

2024-09-19 13:55 UTC, sdirix commented
I noticed one more issue which could be tackled here or in a follow up: Adapting the prompt template directory does not update the AI configuration view.

2024-09-20 08:26 UTC, eneufeld commented
thank you for the test, the found issue should be fixed now

2024-09-20 10:22 UTC, sdirix approved these changes
Works for me! Nice improvements!

2024-09-20 10:51 UTC, JonasHelming approved these changes

2024-09-20 10:51 UTC, merged