Show arguments in tool call response renderer
eclipse-theia/theia pull request #14424
Opened 2024-11-08 23:50 UTC by JonasHelming

fixed #14423

#### What it does

Shows a expandable ">" on tool functions in the hat if they have arguments

#### How to test

run a tool call and look at the chat. E.g.: "How to build this project".
Use a long-running to see the arguments while progress is shown, e.g. "how many files are in the workspace" on a big project such as theia

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2024-11-11 08:39 UTC, planger requested changes
Great idea to show the arguments! Thank you!

However, there are a few things I observed, which I'd like to clarify:

* The arguments are shown again beneath the tool call result (see line 60). Is this on purpose? I found it a bit surprising:
![image](https://github.com/user-attachments/assets/7ec52602-790c-4e27-8537-69cb29f29ff0)

* I think it'd be more clear that `>` is an expandable if we rather use a colored icon instead of the plain `>`, similar to the triangle we use for the entire tool call. The mouse pointer config doesn't really help a lot, because we already set this to `pointer`.

![image](https://github.com/user-attachments/assets/307ab576-9fa9-4866-aef4-74fb170c4743)

* The JSON of the arguments is not really nicely formatted for me.

![image](https://github.com/user-attachments/assets/31153acc-07f3-497a-8e88-14907bd06a75)

* Just a matter of taste, and I don't have a strong opinion on this aspect, but I find those surrounding `[` ... `]` a bit superfluous. Imho there should be as few clutter as possible and it should be as close as possible to normal language without extra technical characters. Only if people are interested in looking into details, those technical details should appear. Which leads me also to the suggestion to show the arguments just as a section of the tool call result if the user unfolded them and not with the rather technical `(>)`? Background is also that this is likely to be used in non-IDE products.

2024-11-11 08:39 UTC, planger commented on packages/ai-chat-ui/src/browser/chat-response-renderer/toolcall-part-renderer.tsx
> +                            textDecoration: 'underline',
We should probably assign a descriptively named class and add these CSS settings to the CSS file for this particularly classed `summary` element.

2024-11-11 08:39 UTC, planger commented on packages/ai-chat-ui/src/browser/chat-response-renderer/toolcall-part-renderer.tsx
> +                <details style={{ display: 'inline' }}>
We should probably assign a descriptively named class and add these CSS settings to the CSS file for this particularly classed `details` element.

2024-11-11 08:39 UTC, planger commented on packages/ai-chat-ui/src/browser/chat-response-renderer/toolcall-part-renderer.tsx
> +                        {this.renderCollapsibleArguments(response.arguments)}
```suggestion
```

Is this duplication of the arguments below the tool call result on purpose? I found it surprising.

2024-11-11 08:41 UTC, planger commented
Sorry, one more thing: It would probably be clearer if we move the `renderCollapsibleArguments` method below the method that calls (`render`) it and make it `protected`.

2024-11-11 16:06 UTC, JonasHelming commented
i decided to leav the "()" in. It looks very weird without them. In a non-technical context, I believe you would need a custom renderer anyways TBH.
A good simple test case is "Show me the package.json" it will have one call without and one with a parameter.

2024-11-20 13:52 UTC, JonasHelming commented
@planger Ping :-)

2024-11-20 15:17 UTC, planger requested changes
Thanks for the revision. However, for me this is now how it looks like (see line break after ...):

![image](https://github.com/user-attachments/assets/a55c75c4-f8ca-46f4-bfaa-d65bc716b010)

Also, if you don't put this in a `pre` element, the pretty printing of the JSON gets lost (see [here](https://github.com/eclipse-theia/theia/pull/14424/files#diff-56b8517f4348e0f66a8ff2f2c9c5c43c5e4c7673d3c9a7ee2910d7a98bbfa17dR60)).

2024-11-21 15:03 UTC, JonasHelming commented
> Thanks for the revision. However, for me this is now how it looks like (see line break after ...):
> 
> ![image](https://private-user-images.githubusercontent.com/588090/388152017-a55c75c4-f8ca-46f4-bfaa-d65bc716b010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDE0ODcsIm5iZiI6MTczMjIwMTE4NywicGF0aCI6Ii81ODgwOTAvMzg4MTUyMDE3LWE1NWM3NWM0LWY4Y2EtNDZmNC1iZmFhLWQ2NWJjNzE2YjAxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxNDU5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGRkMzNkZTA0MTFkNWNmZWIxODFhMTllZmRjNTU2ODAzY2FkZGE1NTdiMTdlMjBlNzZlYTIyOTg1ZmY1MzhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JJkeaNormqesITXwssuQPhDiRBApZqyiNB61UUxsvOg)

This drives me mad. Somehow, I am almost certain, this was not the case when I committed this, and I literally do not find the reason for this. I will continue to search.

> Also, if you don't put this in a `pre` element, the pretty printing of the JSON gets lost (see [here](https://github.com/eclipse-theia/theia/pull/14424/files#diff-56b8517f4348e0f66a8ff2f2c9c5c43c5e4c7673d3c9a7ee2910d7a98bbfa17dR60)).

This was actually on purpose. I you add <pre> then the argument is shown as mutliple lines. However, I am fine with this, too.

2024-11-21 15:43 UTC, planger commented
@JonasHelming Thanks!

> This was actually on purpose. I you add pre then the argument is shown as multiple lines. However, I am fine with this, too.

Ah ok, I was just wondering, because we stringify the JSON with 2 spaces (`undefined, 2`), so I expected the intention was to show it formatted across multiple lines. I'm fine with it either way.

2024-11-26 23:19 UTC, JonasHelming commented
@planger  Looks wonderful now, thank you so much!

2024-11-27 07:51 UTC, planger approved these changes
Thanks, looks good to me! :+1:

2024-11-27 08:01 UTC, merged