All three brackets for variables
eclipse-theia/theia pull request #14465
Opened 2024-11-16 23:21 UTC by JonasHelming

fixed #14464

#### What it does

Allows to use three brackets for variables in prompts. No mixed formats are allows for consistency

#### How to test

There are automated test.
To manually test, 
- open the code completion prompt and a code file. 
- Add one bracket to {{textUntilCurrentPosition}}, see how it fails. 
- Add the second bracket to complete {{{textUntilCurrentPosition}}} and see how it works again. 
- Check that the variable is still listed in the AI configuration view then.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2024-11-19 19:31 UTC, planger requested changes
Thanks, interpreting the variables seem to work fine!

However, the syntax highlighting doesn't work for me:
![image](https://github.com/user-attachments/assets/3b0e98d5-1b89-4fa5-ace9-bd323e17e072)

Also I have a few comments inline above.

2024-11-19 19:31 UTC, planger commented on packages/ai-core/data/prompttemplate.tmLanguage.json
> +}
```suggestion
}

```

2024-11-19 19:31 UTC, planger commented on packages/ai-core/src/common/prompt-service.ts
> +        const matches = this.matchVariables(prompt.template);
Is there a reason why we extract this call of `matchVariablesRegEx()` into a method `this.matchVariables()`? Is this to simplify overriding it by adopters? Not sure this is a very common use case though.

I personally would keep this function call direct and not extract it into a separate method in this class (similar to how we do it in `agent-configuration-widget.tsx`.

If you like to keep the method (`this.matchVariables()`), I wouldn't make it `public` but rather `protected`; if we really want to keep the method at all.

2024-11-19 19:31 UTC, planger commented on packages/ai-core/src/common/prompt-service.ts
> +        const matches = this.matchVariables(prompt.template);
Should we also put the other invocation of `prompt.template.matchAll` into a function for consistency?
See `[...prompt.template.matchAll(PROMPT_FUNCTION_REGEX)]` on line 215.

2024-11-19 19:33 UTC, planger commented on packages/ai-core/src/common/prompt-service.spec.ts
Sorry, this message somehow got lost, readding it:

Nice, thanks for adding additional tests also covering the negative cases now.

I think we may want to avoid duplicating the three tests for the two- and three-bracket cases. This will reduce maintenance effort in the future. I think the following should work (but haven't tested it):

```ts
['{{', '{{{'].forEach((openingBrackets, index) => {
    const closingBrackets = openingBrackets.replace(/{/g, '}'); // Replace each `{` with `}`
    it(`should retrieve raw prompt by id (${index + 2} brackets)`, () => {
        const rawPrompt = promptService.getRawPrompt('8');
        expect(rawPrompt?.template).to.equal(`Hello, ${openingBrackets}name${closingBrackets}`);
    });
});
```

2024-11-19 22:59 UTC, JonasHelming commented
> However, the syntax highlighting doesn't work for me

Should be fixed

2024-11-19 23:01 UTC, JonasHelming commented on packages/ai-core/src/common/prompt-service.spec.ts
I am no sure about this proposal. I agree that the duplication on the tests might require maintenance (if we ever change this). However, I am not a huge fan of making tests with loops instead of clearly writing them out. I think if the test ever break, it will be much easier to understand the test cases if they are simple.

2024-11-20 08:22 UTC, planger approved these changes
Thanks for the revision, works fine now! :+1:

2024-11-20 10:10 UTC, merged