Show more dev container info in title bar
eclipse-theia/theia pull request #14571
Opened 2024-12-03 09:09 UTC by jbicker

#### What it does

Adds info to window title when workspace is loaded in Dev Container and which platform the container is running on.

#### How to test

Start a Dev Container and look up onto the title. There should additionally be something like `[Dev Container @ linux]` 

#### Breaking changes

- [ ] This PR introduces breaking changes and requires careful review. If yes, the breaking changes section in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) has been updated.

#### Attribution

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2024-12-04 16:03 UTC, jonah-iden requested changes

2024-12-06 12:35 UTC, jonah-iden approved these changes
LGTM 👍

2024-12-06 12:35 UTC, jonah-iden commented on packages/core/src/browser/window/window-title-service.ts
> +    @inject(ContributionProvider) @named(WindowTitleContribution) protected readonly titleContributions: ContributionProvider<WindowTitleContribution>;
could you add a line break after the annotations

2024-12-20 10:20 UTC, jbicker commented on packages/core/src/browser/window/window-title-service.ts
> +            const contributions = this.titleContributions.getContributions();
I'll do that in another PR

2024-12-20 10:39 UTC, merged